version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:1597@localhost:5432/movies
    depends_on:
      - db
  db:
    image: postgres:12
    environment:
      - POSTGRES_DB=movies
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1597
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: